    iit_hand:
      # Publish all joint states, including mimic joints -----------------------------------
      joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

      joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_hand_synergy_joint

      joint_trajectory_controller:
        type: position_controllers/JointTrajectoryController
        joints: 
          - right_hand_synergy_joint
      stiffness: 1.0
      deadband: 0.0
